zeebe:
  client:
    cloud:
      clusterId: f0820ac8-55c0-45e1-9410-1016f80b7b4e
      clientId: mun3ndxcfCg7rDq-rxWuFJi7l1.Cz~lY
      clientSecret: ytRc~wagr_rN5GTxS7Bh-renBOf3JfXdmmLOeoLNF9JjunDkmRQCA9Ef0C0Fop2t
      region: lhr-1


